# Generated by Django 4.2.4 on 2023-08-31 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='awards',
        ),
    ]
