# Generated by Django 4.2.4 on 2023-09-01 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_remove_userprofile_awards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
