# Generated by Django 4.2.4 on 2023-09-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('Teacher', 'Teacher'), ('Instructor', 'Instructor'), ('Trainee', 'Trainee'), ('Staff', 'Staff')], max_length=255, null=True),
        ),
    ]
